name: tiktok_clone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.8
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.8
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  animated_splash_screen: ^1.3.0
  video_player: ^2.4.7
  video_compress: ^3.1.1
  timeago: ^3.3.0
  cached_network_image: ^3.2.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

